import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        Map<String, Item> itemMap = new HashMap<>();
        for (Item item: itemRepository.findAll()) {
            itemMap.put(item.getId(), item);
        }
        double totalPrice = 0;
        Map<String, Double> itemCostMap = new HashMap<>();
        String chargeInfo = "============= Order details =============\n";
        for (String input: inputs) {
            String id = input.split("x")[0].trim();
            String countStr = input.split("x")[1].trim();
            int countInt = Integer.valueOf(countStr);
            Item item = itemMap.get(id);
            itemCostMap.put(id, item.getPrice() * countInt);
            totalPrice += item.getPrice() * countInt;
            chargeInfo += String.format("%s x %s = %.0f yuan\n", item.getName(), countStr, countInt*item.getPrice());
        }
        chargeInfo += "-----------------------------------\n";
        double finalPrice = totalPrice;
        String promotionInfo = "";
        for (SalesPromotion sp : salesPromotionRepository.findAll()) {
            if (sp.getType() == "BUY_30_SAVE_6_YUAN"){
                if (totalPrice >= 30 && finalPrice > totalPrice-6){
                    finalPrice = totalPrice - 6;
                    promotionInfo = "满30减6 yuan，saving 6 yuan\n";
                }
            }else if (sp.getType() == "50%_DISCOUNT_ON_SPECIFIED_ITEMS"){
                List<String> relatedItems = sp.getRelatedItems();
                double relatedItemsPrice = 0;
                double temp = totalPrice;
                for (String id : itemCostMap.keySet()) {
                    if (relatedItems.contains(id)){
                        temp -= itemCostMap.get(id);
                        relatedItemsPrice += itemCostMap.get(id);
                    }
                }
                temp = temp + relatedItemsPrice/2;
                if (finalPrice > temp){
                    finalPrice = temp;
                    promotionInfo = String.format("Half price for certain dishes (Braised chicken，Cold noodles)，saving " +
                             "%.0f yuan\n", relatedItemsPrice/2);
                }
            }

        }
        if (finalPrice != totalPrice){
            chargeInfo += "Promotion used:\n" + promotionInfo + "-----------------------------------\n";
        }
        chargeInfo += String.format("Total：%.0f yuan\n" +
                "===================================", finalPrice);
        return chargeInfo;
    }
}
